Support parallel PVTK and PVD files
trixi-framework/ReadVTK.jl pull request #17
Opened 2023-03-01 10:05 UTC by boriskaus

This adds support for `PVD` and `PVTK` files, specifically for `*.pvti`,`*.pvtu` and `*.ptr` files, which allows loading the corresponding parallel file. In the case of structured grids (`ImageData` or `RectiLinearGrid`) the individual pieces of the grid are collected into the full grid.

2023-03-01 16:06 UTC, sloede requested changes
Hi Boris! Thanks again for this great contribution. I am currently on a conference and do not have much time, but most of the implementation looks quite good. This is only the first part of the review though, I still haven't looked at `src/ReadVTK.jl` or `test/pvtk_files.jl`, but hope to do so in the next two days.

2023-03-01 16:06 UTC, sloede commented on src/get_functions.jl
> +See also: [`VTKFile`](@ref)
```suggestion
See also: [`PVTKFile`](@ref)
```

2023-03-01 16:06 UTC, sloede commented on src/get_functions.jl
>  end
I cannot attach this comment to the correct line number, but for all other functions you added a type specialization to the function argument as `vtk_file::VTKFile` for existing methods. For consistency, I think you should also add this to the existing `get_whole_extent` method.

2023-03-01 16:06 UTC, sloede commented on test/runtests.jl
> +  @testset "pvtk files" begin
```suggestion
  @testset "Parallel VTK (PVTK) files" begin
```
Just a little more information for users who are not as familiar with the parallel file formats.

2023-03-01 21:53 UTC, boriskaus commented on src/ReadVTK.jl
> +function isstructured(xml_file::XMLDocument)
ok, didn't know about the 4 spaces. I generally thought that type annotations are better for example to speed up code compilation. In this case the routine won't work if `xml_file` is not an `XMLDocument`, so we might as well add it, not?

2023-03-02 05:11 UTC, sloede commented on src/ReadVTK.jl
> +function isstructured(xml_file::XMLDocument)
Type annotations are really *only* needed to make different *methods* (i.e., "functions with the same name") distinguishable for the compiler. That is, you have a `get_origin(file)` implementation for `file` of type `VTKFile` and a different one for `file` of type `PVTKFile`. In that case, the compiler needs the type annotations `file::VTKFile` etc. to know which version to pick.

Adding a type annotation will _never_ have an impact on performance (at least in all cases that I am aware of).

> In this case the routine won't work if `xml_file` is not an `XMLDocument`, so we might as well add it, not?

We had this discussion in Trixi a few times as well. In many cases it is not clear whether the same implementation could also be used by another type successfully. Therefore, we decided that we will never add type annotations except to make it possible for the compiler to dispatch on the type for different implementations.

2023-03-02 11:00 UTC, sloede requested changes
Second part of my review, addressing mostly the testing setup. `src/ReadVTK.jl` still missing (but hopefully coming soon)

2023-03-02 11:00 UTC, sloede commented on src/get_functions.jl
>      get_whole_extent(vtk_file)
```suggestion
    get_whole_extent(vtk_file::VTKFile)
```
To be consistent with the code.

2023-03-02 11:00 UTC, sloede commented on test/pvtk_files.jl
> +# (2) Read back files
I would really recommend to structure the tests into further `@testset`s. At the very least, I would create one testset for rectilinear, one for image data, one for PVTU, and one for PVD files. The motivation is that this makes it easier in the output of the test runs to figure out what has failed, as it gives you not just the line number but a name attached to it. You could even add more than one layer of `@testset`s, but at least the main parts I would separate into separate testsets

2023-03-02 11:00 UTC, sloede commented on test/pvtk_files.jl
> +      ) do pvtk
I attach this here but it really applies to multiple locations:

I strongly recommend to remove all files that are generated by your tests in the beginning, and then again at the end. This way, you minimize the chance of accidentally ending up with an old test file that was generated during a previous run and which could compromise the validity of subsequent test runs.

For this purpose, we create a test file directory in
https://github.com/trixi-framework/ReadVTK.jl/blob/3abe6b8b87bf1e79ec8f34de2158bc20fa5331f2/test/runtests.jl#L19-L21
and delete it at the end again
https://github.com/trixi-framework/ReadVTK.jl/blob/3abe6b8b87bf1e79ec8f34de2158bc20fa5331f2/test/runtests.jl#L373.

If you use a path to the test directory here and in the other locations, you will automatically have everything removed in the end again:
```suggestion
  path = joinpath(TEST_EXAMPLES_DIR, "fields")
  saved_files[part] = pvtk_grid(
          path, Vector(xs), Vector(ys), Vector(zs);
          part = part, extents = extents,
      ) do pvtk
```
See also e.g. here:
https://github.com/trixi-framework/ReadVTK.jl/blob/3abe6b8b87bf1e79ec8f34de2158bc20fa5331f2/test/runtests.jl#L347-L350

2023-03-02 14:28 UTC, boriskaus commented on test/pvtk_files.jl
> +      ) do pvtk
yes, very good point - thanks!

2023-03-02 14:32 UTC, boriskaus commented on test/pvtk_files.jl
> +# (2) Read back files
good point; I've added that

2023-03-06 21:02 UTC, sloede requested changes
I finally got to the last part of the review. There were many many changes in this PR, thus there are quite a few comments 😬 Please consider most of them as suggestions (unless indicated otherwise); they are mostly to make the style and variable names consistent with the rest of the code.

In case of questions, please let me know!

In any case, great work!

2023-03-06 21:02 UTC, sloede commented on src/ReadVTK.jl
> +
```suggestion
```

2023-03-06 21:02 UTC, sloede commented on src/ReadVTK.jl
> +  get_coordinates(pvtk_file::{VTKFile; x_string="x", y_string="y", z_string="z")
```suggestion
    get_coordinates(pvtk_file::{VTKFile; x_string="x", y_string="y", z_string="z")
```

2023-03-06 21:02 UTC, sloede commented on src/ReadVTK.jl
> +
```suggestion
```

2023-03-07 08:14 UTC, boriskaus commented on src/ReadVTK.jl
> +struct PVTKFile{N}
ok, I've changed that

2023-03-07 08:39 UTC, boriskaus commented on src/ReadVTK.jl
> +  end
ok fine. didn't worked initially but does now

2023-03-07 08:41 UTC, boriskaus commented on src/ReadVTK.jl
> +  parent_xml::XMLDocument
agree

2023-03-07 08:59 UTC, boriskaus commented on src/ReadVTK.jl
> +  dat = []
ok, done now

2023-03-07 09:05 UTC, boriskaus commented on src/ReadVTK.jl
> +  timestep = Vector{Float64}(undef,N)
changed

2023-03-07 09:24 UTC, boriskaus commented
Unless I missed some, I believe that all suggestions are now implemented - thanks a lot for that!

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  return PVTKFile(filename, xml_file, file_type, version, vtk_filenames, vtk)
```suggestion
  # Extract names of files & load the data
  pieces   = root[file_type][1]["Piece"]
  n_pieces = length(pieces)
  vtk_filenames = Vector{String}(undef, n_pieces)  
  vtk_files = Vector{VTKFile}(undef, n_pieces)  
  
  for i in 1:n_pieces
    vtk_filenames[i] = attribute(pieces[i], "Source", required=true)
    vtk_files[i] = VTKFile(joinpath(dir, vtk_filenames[i]))
  end

  return PVTKFile(filename, xml_file, file_type, version, vtk_filenames, vtk_files)
```
For consistency

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  return PVDFile(filename, file_type, file, dir, timestep)
```suggestion
  # Extract names of files & load the data
  pieces = root[file_type][1]["DataSet"]
  n_pieces = length(pieces)
  vtk_filenames = Vector{String}(undef, n_pieces)  
  directories = Vector{String}(undef, n_pieces)  
  timesteps = Vector{Float64}(undef, n_pieces)
  
  for i in 1:n_pieces
    file_dir = attribute(pieces[i], "file", required=true)
    vtk_filenames[i] = file_dir
    directories[i] = dirname(file_dir)
    timesteps[i] = parse(Float64, attribute(pieces[i], "timestep", required=true))
  end

  return PVDFile(filename, file_type, vtk_filenames, directories, timesteps)
```
For consistency

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  for i=1:N
```suggestion
  n_files = length(pvtk_file)
  cdata_v = Vector{VTKData}(undef, n_files)
  for i in 1:n_files
```
For consistency

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  for i in 1:N
```suggestion
  n_files = length(pvtk_file)
  pdata_v = Vector{VTKData}(undef, n_files)
  for i in 1:n_files
```
For consistency

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  for i=1:N
```suggestion
  n_datasets = length(data.data)
  data_array = Vector{VTKDataArray}(undef, n_datasets)
  for i in 1:n_datasets
```
For consistency

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  for i in 1:N
```suggestion
  n_datasets = length(data_array.data)
  dat = Vector{Array}(undef, n_datasets)  
  for i in 1:n_datasets
```
For consistency

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  return dat
```suggestion
  end
  
  return dat
```
For consistency

2023-03-07 10:41 UTC, sloede commented on src/ReadVTK.jl
> +  for i=2:N
```suggestion
function get_coordinates(pvtk_file::PVTKFile; x_string="x", y_string="y", z_string="z")
  coords =  get_coordinates.(pvtk_file.vtk_files,x_string=x_string, y_string=y_string, z_string=z_string);

  x,y,z = coords[1][1][:],coords[1][2][:],coords[1][3][:]
  for i=2:length(pvtk_file)
```
Simplify

2023-03-07 10:43 UTC, sloede approved these changes
LGTM! Thanks a lot for the great contribution @boriskaus! Once all tests pass and if the code coverage numbers look ok, this can be merged.

2023-03-07 10:51 UTC, merged