Support for StructuredGrid files
trixi-framework/ReadVTK.jl pull request #18
Opened 2023-03-06 11:27 UTC by boriskaus

This PR adds support for `StructuredGrid` (`*.vts`) files.
Note that I did not finalise the `PStructuredGrid` files yet, as this depends on PR #17.

2023-03-07 06:47 UTC, sloede commented
It seems like this PR contains the changes from #17 as well. I will thus wait with a review until #17 is merged into `main` and `main` then merged into this PR here. Feel free to ping me once this is ready for review 🙂

2023-03-07 18:13 UTC, boriskaus commented
@sloede: It's a bit mysterious why the last CI run failed (nothing to do with the package, it seems). Anyways, I now merged `main`, so it is ready for you to have a look at.

2023-03-08 06:30 UTC, sloede requested changes
Thanks for the nice contribution again, @boriskaus! I have left a few comments and suggestions but nothing wild, thus I think this can be cleaned up easily for merging...

2023-03-08 06:30 UTC, sloede commented on test/pvtk_files.jl
> +  pvd = PVDFile("examples/full_simulation.pvd")
Ah, should this maybe be something like
```suggestion
  pvd = PVDFile(joinpath(TEST_EXAMPLES_DIR, "full_simulation.pvd"))
```
?

2023-03-08 06:30 UTC, sloede commented on src/ReadVTK.jl
> +  if !(file_type in ("PImageData", "PRectilinearGrid","PUnstructuredGrid", "PStructuredGrid"))
```suggestion
  if !(file_type in ("PImageData", "PRectilinearGrid", "PUnstructuredGrid", "PStructuredGrid"))
```

2023-03-08 06:30 UTC, sloede commented on src/ReadVTK.jl
> +
```suggestion
  coordinates = get_coordinate_data(vtk_file)
  x = get_data(coordinates[x_string])
  y = get_data(coordinates[y_string])
  z = get_data(coordinates[z_string])
```
It does not make sense to put this in an if condition, since it was already checked in lines 909ff that this mist be a file of type `RectilinearGrid`. Or am I misssing something?

2023-03-08 06:30 UTC, sloede commented on src/ReadVTK.jl
> +
```suggestion
```
No blank lines at the end of a block

2023-03-08 06:30 UTC, sloede commented on src/ReadVTK.jl
> +  if pvtk_file.file_type== "PStructuredGrid"
```suggestion
  if pvtk_file.file_type == "PStructuredGrid"
```

2023-03-08 06:30 UTC, sloede commented on src/ReadVTK.jl
> +  elseif pvtk_file.file_type== "PRectilinearGrid"
```suggestion
  elseif pvtk_file.file_type == "PRectilinearGrid"
```

2023-03-08 06:30 UTC, sloede commented on src/ReadVTK.jl
>    end
I think there should also be an `else` condition with an error that is triggered when `get_coordinates` is called with a PVTKFile that is neither of type "PStructuredGrid" nor of type "PRectilinearGrid". Otherwise, in the current implementation you will get an error that the variables x, y, z have not been defined, which is not very helpful for the user unless they look into the implementation details

2023-03-08 07:06 UTC, boriskaus commented on src/ReadVTK.jl
> +
correct

2023-03-08 07:09 UTC, boriskaus commented on src/ReadVTK.jl
>    end
fair enough; added that

2023-03-08 07:11 UTC, boriskaus commented on test/pvtk_files.jl
> +  pvd = PVDFile("examples/full_simulation.pvd")
yes I think that is it. Not sure why the test was not failing...

2023-03-08 07:11 UTC, boriskaus commented on test/structuredgrid.jl
> +      [y[i,j] = sqrt(j/Nj) for i = 1:Ni, j = 1:Nj]
yup

2023-03-08 07:56 UTC, boriskaus commented
I've implemented it all, and it seems to run fine. 
I see that you only test on Julia 1.6; perhaps an idea to also add a more recent version of Julia there (I know it should be backwards compatible, but you never know).

2023-03-08 08:03 UTC, sloede commented on src/ReadVTK.jl
> +    error("The file type of the VTK file must be 'RectilinearGrid' (current: $(vtk_file.file_type)).")
```suggestion
    error("The file type of the VTK file must be 'RectilinearGrid' or 'StructuredGrid' (current: $(vtk_file.file_type)).")
```

2023-03-08 08:09 UTC, sloede approved these changes
Great work, again, LGTM! Once tests pass and coverage is ok, this can be merged...

2023-03-08 08:10 UTC, sloede commented
Ah, there seems to be an error with at least one of the tests...

2023-03-08 08:14 UTC, boriskaus commented
Hmm, I had the same error a while ago. It started when I introduced `local x,y,z` in `structuredgrid.jl` but seems to trigger an error in a completely different test. I have no idea why that would be.

2023-03-08 10:27 UTC, boriskaus commented
So [this](https://github.com/trixi-framework/ReadVTK.jl/actions/runs/4363300105/jobs/7629232436#step:6:130) mistake sometimes occurs in CI and sometimes not, even when we cleanup the files altogether. I don't like this at all...

2023-03-08 11:00 UTC, sloede commented
> So [this](https://github.com/trixi-framework/ReadVTK.jl/actions/runs/4363300105/jobs/7629232436#step:6:130) mistake sometimes occurs in CI and sometimes not, even when we cleanup the files altogether. I don't like this at all...

Can you try fixing it? It seems to me like a very specific error, not related to floating point truncation.

2023-03-08 11:02 UTC, boriskaus commented
I have no clue where to start. Seems that the files written to disc sometimes have a different size. Not having a local machine that reproduces this error does not help..

2023-03-08 17:43 UTC, boriskaus commented
Note that the main branch is also failing with what feels to be a fairly similar problem.

2023-03-09 08:02 UTC, boriskaus commented
@sloede: Whereas CI is fine now, the error remains weird and occurs when reading compressed data back from a file [here](https://github.com/trixi-framework/ReadVTK.jl/blob/c13c2c124f006843f9fba05db15dc30a837eb322/src/ReadVTK.jl#L665):
```julia
raw = data_array.vtk_file.appended_data
HeaderType = header_type(data_array.vtk_file)
if is_compressed(data_array)
   # If data is stored compressed, the first four integers of type `header_type` are the header and
   # the fourth value contains the number of bytes to read
   first = data_array.offset + 1
   last = data_array.offset + 4 * sizeof(HeaderType)
   header = Int.(reinterpret(HeaderType, raw[first:last]))
   n_bytes = header[4]

   first = data_array.offset + 4 * sizeof(HeaderType) + 1
   last = first + n_bytes - 1
   uncompressed = transcode(ZlibDecompressor, raw[first:last])
else
   ...
end
``` 
in some cases, the length of the `raw` vector is shorter than `last` as indicated in the header. The CI failure in the `main` branch seems to be caused by the same [issue](https://github.com/trixi-framework/ReadVTK.jl/actions/runs/4363069490/jobs/7628712036). 
In my last commit, I simply added an error message when this occurs, but it doesn't cure the cause of it.

Are there perhaps changes in the upstream packages that could cause this?

2023-03-09 10:12 UTC, sloede commented
> in some cases, the length of the `raw` vector is shorter than `last` as indicated in the header. The CI failure in the `main` branch seems to be caused by the same [issue](https://github.com/trixi-framework/ReadVTK.jl/actions/runs/4363069490/jobs/7628712036). In my last commit, I simply added an error message when this occurs, but it doesn't cure the cause of it.

Thanks for investigating the issue. Do you know why the error now disappeared? And did it only occur in cases where the file in question was generated on-the-fly or also in cases where an existing vtk file is used?

> Are there perhaps changes in the upstream packages that could cause this?

I believe we had a similar issue before - @andrewwinters5000 do you still remember where and when this occurred? I do not remember what we did back then to resolve it, but I recall that we had a similar issue of files being "truncated" by the zip/unzip mechanism.

2023-03-09 10:24 UTC, sloede commented on test/runtests.jl
> +      clean_directory(TEST_EXAMPLES_DIR)
```suggestion
```
I think it should be sufficient to recreate the test dir once per top-level testset, not in each individual testset as well

2023-03-09 11:00 UTC, ranocha commented
> > in some cases, the length of the `raw` vector is shorter than `last` as indicated in the header. The CI failure in the `main` branch seems to be caused by the same [issue](https://github.com/trixi-framework/ReadVTK.jl/actions/runs/4363069490/jobs/7628712036). In my last commit, I simply added an error message when this occurs, but it doesn't cure the cause of it.
> 
> Thanks for investigating the issue. Do you know why the error now disappeared? And did it only occur in cases where the file in question was generated on-the-fly or also in cases where an existing vtk file is used?
> 
> > Are there perhaps changes in the upstream packages that could cause this?
> 
> I believe we had a similar issue before - @andrewwinters5000 do you still remember where and when this occurred? I do not remember what we did back then to resolve it, but I recall that we had a similar issue of files being "truncated" by the zip/unzip mechanism.


I also vaguely remember some spurious issues like these. If I remember correctly, they had some stochastic part, i.e., they were not triggered every time - maybe depending on the GitHub runners etc.? Some parts may have been specific to Windows or so...

2023-03-09 11:36 UTC, boriskaus commented
> > in some cases, the length of the `raw` vector is shorter than `last` as indicated in the header. The CI failure in the `main` branch seems to be caused by the same [issue](https://github.com/trixi-framework/ReadVTK.jl/actions/runs/4363069490/jobs/7628712036). In my last commit, I simply added an error message when this occurs, but it doesn't cure the cause of it.
> 
> Thanks for investigating the issue. Do you know why the error now disappeared? 
No, if you look at the various CI's of yesterday, it sometimes appears and sometimes not (on different systems)

> And did it only occur in cases where the file in question was generated on-the-fly or also in cases where an existing vtk file is used?
I believe it is only with cases where the file was generated on-the-fly.

> 
> > Are there perhaps changes in the upstream packages that could cause this?
> 
> I believe we had a similar issue before - @andrewwinters5000 do you still remember where and when this occurred? I do not remember what we did back then to resolve it, but I recall that we had a similar issue of files being "truncated" by the zip/unzip mechanism.

2023-03-09 11:39 UTC, sloede commented
OK. Since the error seems to have disappeared, once the last remaining issues are resolved, we can merge this.

2023-03-09 13:27 UTC, boriskaus commented on src/ReadVTK.jl
> +    end
yes indeed, this error message was in the wrong routine. Will upload a fix

2023-03-09 14:02 UTC, boriskaus commented
so we now have 1 failed CI and 2 that passed, with the only thing that changed being:
```Julia
@show data_array data_array.vtk_file.xml_file
```
and removing:
```Julia
# Start with a clean environment: remove example file directory if it exists
isdir(TEST_EXAMPLES_DIR) && rm(TEST_EXAMPLES_DIR, recursive=true)
mkpath(TEST_EXAMPLES_DIR)
```
It seems to be rather stochastic and I have no idea where to look.
I guess we can probably merge (and increment the version number) and see if it keeps occurring.

2023-03-09 14:10 UTC, ranocha commented
> It seems to be rather stochastic and I have no idea where to look.

That's also what I remember from similar issues earlier - it's stochastic and when it fails, it's on Windows.

> I guess we can probably merge (and increment the version number) and see if it keeps occurring.

Sounds good to me. Thanks a lot for your contributions!

2023-03-09 20:44 UTC, sloede approved these changes

2023-03-09 21:13 UTC, merged